### ISSUE TITLE
Wrong HSB Format

### ISSUE THREAD

**Issue by fabik111** [pjpmarques/ChainableLED#3]
I'm using this lib with HSB color format, when Brightness is set at 100% or 1.0 (according lib convention) the led color is always white (like HSL color format) instead of full color. So the method `setColorHSB`  is in HSL color format not HSB. [Check this site]( http://colorizer.org/)

**Comment by pjpmarques** [comment]
You are absolutely correct. I don't know how this happened. The routine had been [adapted from here](https://gist.github.com/mjackson/5311256) but, somehow, instead of putting HSL I've put HSB. Probably because they are similar.

**Comment by pjpmarques** [comment]
Refactored the code so that HSB became HSL.
